version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  build_and_test:
    jobs:
      - build-and-code-check
      - test-no-kafka:
          requires: [build-and-code-check]
      - test-with-kafka:
          matrix:
            parameters:
              python-version: ["3.11", "3.9"]
          requires: [test-no-kafka]

jobs:
  build-and-code-check:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Lint and format
          command: |
            pip install .[test]
            pyflakes openmsistream
            black --check .
            pylint openmsistream test

  test-no-kafka:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run unit tests (no Kafka)
          command: |
            pip install .[test]
            pytest -m "not kafka" -k "not encrypted" \
              --junitxml=test-results/results.xml \
              --cov=openmsistream \
              --cov-report=html:test-results/htmlcov \
              --cov-report=xml:coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/htmlcov
          destination: coverage-report
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

  test-with-kafka:
    parameters:
      python-version:
        type: string
        default: "3.9"
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Set Python version
          command: |
            pyenv install -s << parameters.python-version >>
            pyenv global << parameters.python-version >>
      - run:
          name: Run integration tests (with Kafka)
          command: |
            pip install .[test]
            pytest -m kafka \
              --junitxml=test-results/results.xml \
              --cov=openmsistream \
              --cov-append \
              --cov-report=html:test-results/htmlcov \
              --cov-report=xml:coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/htmlcov
          destination: coverage-report
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml
