version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  build_and_test:
    jobs:
      - lint
      - test-no-kafka:
          requires: [lint]
      - test-with-kafka:
          requires: [test-no-kafka]

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Lint and format
          command: |
            pip install .[test]
            pyflakes openmsistream
            black --check .
            pylint openmsistream test

  test-no-kafka:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run unit tests (no Kafka)
          command: |
            pytest -m "not kafka" --junitxml=test-results/results.xml
      - store_test_results:
          path: test-results

  test-with-kafka:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run integration tests (with Kafka)
          command: |
            pytest -m kafka --junitxml=test-results/results.xml
      - store_test_results:
          path: test-results
