version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  build_and_test:
    jobs:
      - lint
      - test-no-kafka:
          requires: [lint]
      - test-with-kafka:
          requires: [test-no-kafka]

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Lint and format
          command: |
            pip install .[test]
            pyflakes openmsistream
            black --check .
            pylint openmsistream test

  test-no-kafka:
    docker:
      - image: cimg/python:3.11
    environment:
      KAFKA_TEST_CLUSTER_BOOTSTRAP_SERVERS: "localhost:9092"
      KAFKA_TEST_CLUSTER_USERNAME: "dummy"
      KAFKA_TEST_CLUSTER_PASSWORD: "dummy"
    steps:
      - checkout
      - run:
          name: Run unit tests (no Kafka)
          command: |
            pip install .[test]
            pytest -m "not kafka" -k "not encrypted" \
              --junitxml=test-results/results.xml \
              --cov=openmsistream \
              --cov-report=html:test-results/htmlcov \
              --cov-report=xml:coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/htmlcov
          destination: coverage-report
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

  test-with-kafka:
    machine:
      image: ubuntu-2204:current
    environment:
      USE_LOCAL_KAFKA_BROKER_IN_TESTS: "yes"
    steps:
      - checkout
      - run:
          name: Set Python version
          command: pyenv global $(pyenv versions --bare | grep -E '^3\.(11|12|13)' | sort -V | tail -1)
      - run:
          name: Run integration tests (with Kafka)
          command: |
            pip install .[test]
            pytest -m kafka -k "not encrypted" \
              --junitxml=test-results/results.xml \
              --cov=openmsistream \
              --cov-append \
              --cov-report=html:test-results/htmlcov \
              --cov-report=xml:coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/htmlcov
          destination: coverage-report
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml
